# if(DEFINED TRIBO_PERF_COMPARE)
include(ExternalProject)
ExternalProject_Add(
  ${CMAKE_PROJECT_NAME}-perf

  GIT_REPOSITORY "${CMAKE_SOURCE_DIR}/.git"
  GIT_TAG "main"

  CMAKE_ARGS -DTRIBO_ENABLE_BENCH=1 -DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_PROJECT_NAME}-perf

  INSTALL_COMMAND ""
  UPDATE_COMMAND ""
  PATCH_COMMAND ""
  TEST_COMMAND ""

  GIT_SHALLOW ON
)

# endif()
