
set(TRIBO_EXPORT_HEADER_DIR ${PROJECT_SOURCE_DIR}/include)
set(TRIBO_EXPORT_HEADER ${TRIBO_EXPORT_HEADER_DIR}/tribo.h)
set(TRIBO_EXPORT_MACRO TRIBO_EXPORT_API)

if(
  DEFINED PROJECT_VERSION_MAJOR AND
  DEFINED TRIBO_GIT_COMMIT_HASH AND
  DEFINED TRIBO_GIT_BRANCH_NAME AND
  DEFINED TRIBO_GIT_COMMIT_NUMBER
)
  set(TRIBO_PROJECT_VERSION_DEFINES
    TRIBO_PROJECT_VERSION_MAJOR=${PROJECT_VERSION_MAJOR}
    TRIBO_PROJECT_VERSION_MINOR=${PROJECT_VERSION_MINOR}
    TRIBO_PROJECT_VERSION_PATCH=${PROJECT_VERSION_PATCH}
    TRIBO_GIT_COMMIT_HASH=\"${TRIBO_GIT_COMMIT_HASH}\"
    TRIBO_GIT_BRANCH_NAME=\"${TRIBO_GIT_BRANCH_NAME}\"
    TRIBO_GIT_COMMIT_NUMBER=${TRIBO_GIT_COMMIT_NUMBER}
  )
else()
  message(FATAL_ERROR "Necessary macros not defined.")
endif()
