doc:
  - changed-files:
      - any-glob-to-any-file: doc/**

ci-cd:
  - changed-files:
      - any-glob-to-any-file: .github/**

tools:
  - changed-files:
      - any-glob-to-any-file: ["scripts/**", "*"]

src:
  - changed-files:
      - any-glob-to-any-file: "**/src/**"

main:
  - changed-files:
      - any-glob-to-any-file: "components/main/**"

test:
  - changed-files:
      - any-glob-to-any-file: "**/test/**"
