ExternalProject_Add(
  cmake
  DEPENDS ninja
  GIT_REPOSITORY https://gitlab.kitware.com/cmake/cmake.git
  GIT_TAG master
  GIT_PROGRESS TRUE
  GIT_SHALLOW TRUE
  CMAKE_GENERATOR "Ninja"
  SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/cmake
  CMAKE_ARGS
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_MAKE_PROGRAM=${TRIBO_NINJA_PATH}
  -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
  -DBUILD_TESTING=OFF
)
