if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
  set(TRIBO_NO_WARN_FLAG /w)
  set(TRIBO_STANDARD_WARNINGS /W4)

  set(TRIBO_ASAN_COMPILER_FLAG /fsanitize=address)
  set(TRIBO_ASAN_LINKER_FLAG /fsanitize=address)
  set(TRIBO_CODE_COVERAGE_LINKER_FLAG /PROFILE)
endif()
