LINKFLAGS_COMMON = /NOLOGO /TIME /IGNORE:4001 /INCREMENTAL:NO /SUBSYSTEM:CONSOLE /MACHINE:$(ARCH)
LINKFLAGS_DEBUG = $(RUNTIME_LIB_DEBUG) $(LINKFLAGS_COMMON) /DEBUG:FULL
LINKFLAGS_RELEASE = $(RUNTIME_LIB_RELEASE) $(LINKFLAGS_COMMON) /LTCG /LTCG:STATUS
