ARCH = $(VSCMD_ARG_TGT_ARCH)

CFLAGS = /std:c11 /nologo /W4 /WX /external:W0 /permissive- /diagnostics:caret /FC -D_CRT_SECURE_NO_WARNINGS
LDFLAGS = /nologo /WX
ARFLAGS = /nologo

AVX2_FLAG = /arch:AVX2
AVX512_FLAG = /arch:AVX512

!INCLUDE compiler.mk
!INCLUDE link.mk
!INCLUDE tidy.mk

!IF "$(DEBUG)" == "1"
CFLAGS = /Od /Zi $(CFLAGS) $(RUNTIME_FLAG_DEBUG) $(CFLAGS_DEBUG)
LDFLAGS = $(LDFLAGS) $(LDFLAGS_DEBUG) /link $(LINKFLAGS_DEBUG) $(LINKFLAGS)
!ELSE
CFLAGS = /FAs $(CFLAGS) $(RUNTIME_FLAG_RELEASE) $(CFLAGS_RELEASE)
LDFLAGS = $(LDFLAGS) $(LDFLAGS_RELEASE) /link $(LINKFLAGS_RELEASE) $(LINKFLAGS)
!ENDIF

LDFLAGS = $(strip $(LDFLAGS))
