# Linker flags. Apply to both LINK and LLD-LINK on windows.
LINKFLAGS_COMMON = /NOLOGO /TIME /WX /NOIMPLIB /machine:$(ARCH) /DEBUG:FULL
LINKFLAGS_DEBUG = $(LINKFLAGS_COMMON)
LINKFLAGS_RELEASE = $(LINKFLAGS_COMMON) /INCREMENTAL:NO /LTCG:STATUS /LTCG

# Linker flags - static library.
ARFLAGS_COMMON = /NOLOGO /WX /machine:$(ARCH)
ARFLAGS_DEBUG = $(ARFLAGS_COMMON)
ARFLAGS_RELEASE = /LTCG $(ARFLAGS_COMMON)
