# Linker flags. Apply to both LINK and LLD-LINK on windows.
LINKFLAGS_COMMON = /NOLOGO /TIME /WX /NOIMPLIB /machine:$(ARCH)
LINKFLAGS_DEBUG = $(LINKFLAGS_COMMON) /DEBUG:FULL
LINKFLAGS_RELEASE = $(LINKFLAGS_COMMON) /DEBUG:FULL /INCREMENTAL:NO /LTCG:STATUS /LTCG

# Linker flags - static library.
ARFLAGS_COMMON = /NOLOGO /WX
ARFLAGS_DEBUG = $(ARFLAGS_COMMON)
ARFLAGS_RELEASE = /LTCG /LTCG:STATUS $(ARFLAGS_COMMON)
