#* GitHub x64 cloud runners.
name: Build & Test - GitHub Runners

#* For a pull request, we use the PR title. After a push (probably to main), we use the commit title.
run-name: ${{ github.actor }} - ${{ github.event.head_commit.message || github.event.pull_request.title }}

#* To avoid duplicate jobs running when both push and PR is satisfied, we use this:
#* https://github.com/orgs/community/discussions/26940#discussioncomment-5686753
on:
  push:
    branches:
      - main
  pull_request:

#* Stop stale workflows when pull requests are updated: https://stackoverflow.com/a/70972844
#* Does not apply to the main branch.
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latestrc
          ninjaVersion: latest
      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: "17"
          env: true
      - run: cmake --workflow --preset clang-code-check
      - run: cmake --workflow --preset gcc-code-check

  #* MacOS with clang (from homebrew).
  macos-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latestrc
          ninjaVersion: latest
      - run: brew update
      - run: brew install llvm@17
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
      - run: echo "$(brew --prefix llvm@17)/bin" >> $GITHUB_PATH
      - run: cmake --workflow --preset clang-code-check

  windows-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latestrc
          ninjaVersion: latest
      - run: choco upgrade llvm --version=17.0.6
      - run: cmake --workflow --preset clang-code-check
      - run: cmake --workflow --preset clang-cl-code-check
      - run: cmake --workflow --preset msvc-code-check
