#* GitHub x64 cloud runners.
name: Build & Test - GitHub Runners

#* For a pull request, we use the PR title. After a push (probably to main), we use the commit title.
run-name: ${{ github.actor }} - ${{ github.event.head_commit.message || github.event.pull_request.title }}

#* To avoid duplicate jobs running when both push and PR is satisfied, we use this:
#* https://github.com/orgs/community/discussions/26940#discussioncomment-5686753
on:
  push:
    branches:
      - main
  pull_request:

#* Stop stale workflows when pull requests are updated: https://stackoverflow.com/a/70972844
#* Does not apply to the main branch.
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  linux-x64-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest
      - uses: ssciwr/doxygen-install@v1
        with:
          version: "1.9.8"
      - name: Install LLVM-17 and gcovr
        run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && brew install llvm@17 gcovr
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
      - name: Build project (clang-code-check)
        run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && cmake --workflow --preset clang-code-check

  macos-x64-clang:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest
      - uses: ssciwr/doxygen-install@v1
        with:
          version: "1.9.8"
      - run: brew update
      - name: Install LLVM-17 and gcovr
        run: brew install llvm@17 gcovr
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
      - name: Add LLVM-17 to path over system clang
        run: echo "$(brew --prefix llvm@17)/bin" >> $GITHUB_PATH
      - name: Build project (clang-code-check)
        run: cmake --workflow --preset clang-code-check
        env:
          LDFLAGS: "-L$(brew --prefix llvm@17)/lib/c++ -Wl,-rpath,$(brew --prefix llvm@17)/lib/c++ -L$(brew --prefix llvm@17)/lib"
          CPPFLAGS: "-I$(brew --prefix llvm@17)/include"

  windows-x64-clang:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest
      - uses: ssciwr/doxygen-install@v1
        with:
          version: "1.9.8"
      - name: Install gcovr
        run: pip install gcovr
      - name: Install LLVM-17
        run: choco upgrade llvm --version=17.0.6
      - name: Build project (clang-code-check)
        run: cmake --workflow --preset clang-code-check

  windows-x64-clang-cl:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest
      - uses: ssciwr/doxygen-install@v1
        with:
          version: "1.9.8"
      - name: Install gcovr
        run: pip install gcovr
      - name: Install LLVM-17
        run: choco upgrade llvm --version=17.0.6
      - name: Build project (clang-cl-code-check)
        run: cmake --workflow --preset clang-cl-code-check

  windows-x64-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest
      - uses: ssciwr/doxygen-install@v1
        with:
          version: "1.9.8"
      - name: Build project (msvc-code-check)
        run: cmake --workflow --preset msvc-code-check
