# Perform checks on pull requests.
name: PR Checks
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Pass pull request title through script.
        run: python3 ./.github/checks/pr-title.py "${{ github.event.pull_request.title }}"
      - name: Pass pull request body through script.
        run: python3 ./.github/checks/pr-body.py "${{ github.event.pull_request.body }}"
      - name: Pass pull request commit message through script.
        run: python3 ./.github/checks/commit-msg.py "${{ github.event.pull_request.head.sha }}"
      - name: Label pull request
        uses: actions/labeler@v5
        with:
          sync-labels: true
