on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  #* Check PR title if PR.
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pass pull request title through script.
        run: python3 ./tools/pull-request-checks/title.py "${{ github.event.pull_request.title }}"
      - name: Pass pull request body through script.
        run: python3 ./tools/pull-request-checks/body.py "${{ github.event.pull_request.body }}"
      - name: Pass num-commits through script.
        run: python3 ./tools/pull-request-checks/num-commits.py ${{ github.event.pull_request.commits }}
